---
Standards:
  -
    Title: CS Fundamentals Overview
    Description: Overview and links
    UID: ffe615ec-8c18-48a2-8a12-5fa54aa0214d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: d75af4a1-ff7d-46b9-988d-8fcda5d75bc5
        Path: /00-about-thursdays-at-ada/about-thursdays-at-ada.md
      -
        Type: Lesson
        UID: bcc6309e-3453-4aea-9b22-ef8e09c2b09e
        Path: /00-about-thursdays-at-ada/norms.md
  -
    Title: Approaching Problems
    Description: Problem Solving, Big O Notation
    UID: 9141935e-3d6b-4f83-9eef-eca929c19ad6
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 213deeac-736c-42e9-a774-1d904d87991e
        Path: /01-Problem-Solving-And-Big-O/01-problem-solving.md
      -
        Type: Lesson
        UID: 50bd3c42-38f2-461b-a832-9f79fa501d62
        Path: /01-Problem-Solving-And-Big-O/02-big-o.md
      -
        Type: Instructor
        UID: 82ebf9b5-71c2-4935-b81c-545187672ef9
        Path: /01-Problem-Solving-And-Big-O/class-lesson.instructor.md
      -
        Type: Lesson
        UID: d108fdc2-000e-493a-9120-fcdd7c6b4fb9
        Path: /01-Problem-Solving-And-Big-O/04-in-class-problemset.md
      -
        Type: Checkpoint
        UID: 25f55d56-003a-4af1-b968-4bfc07888ad7
        Path: /01-Problem-Solving-And-Big-O/03-problem-solving-checkpoint.md
  -
  
    Title: Linked Lists
    Description: Linked Lists
    UID: 8e6f54bf-41e8-41d6-9a03-dca103bf15ed
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: c498e182
        Path: /02-linked-lists/linked-lists.instructor.md
      -
        Type: Lesson
        UID: 99474aeb-183e-4f01-990b-0a689c022c30
        Path: /02-linked-lists/01-linked-lists.md
      -
        Type: Lesson
        UID: 99474aeb-183e-4f01-990b-0a689c022c30
        Path: /02-linked-lists/02-linked-list-activity.md
      -
        Type: Checkpoint
        UID: e1d0e2c0-acb2-436a-b329-8c3da5155443
        Path: /02-linked-lists/03-linked-list-checkpoint.md
  -
    Title: Binary Search Trees
    Description: Binary Search Trees
    UID: fc8d8eae-2456-4b22-9213-127d6e83dd5e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: e153ec41-477e-43fb-bf6d-0173e24aec85
        Path: /03-Binary-Search-Trees/bst.instructor.md
      -
        Type: Lesson
        UID: d363c5cb-af6d-45d1-8e98-eaf960f8fac9
        Path: /03-Binary-Search-Trees/01-Binary-Search-Trees.md
      -
        Type: Checkpoint
        UID: bbf1e2a2-0d6e-4337-9b00-81216688e16a
        Path: /03-Binary-Search-Trees/02-Bst-checkpoint.md
  -
    Title: Stacks And Queues
    Description: Stacks And Queues
    UID: 48065b1f-127a-4434-8029-d3e8f2098694
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 4710249d-f9f4-4943-ac42-7688a34232b3
        Path: /04-Stacks-And-Queues/01-stacks-and-queues.md
      -
        Type: Checkpoint
        UID: 13fd1a26-237c-4d3c-884d-575408019668
        Path: /04-Stacks-And-Queues/02-stacks-and-queues-checkpoint.md
  -
    Title: Hash Tables
    Description: How hashes work
    UID: 0ae273c2-90b1-4ec0-9738-1296f9ccfe08
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: b1b69d98-9fb4-4b91-9eb1-2cfbcf4d1046
        Path: /05-hash-tables/01-hash-tables.md
      -
        Type: Checkpoint
        UID: a39c4928-599f-43b9-9b01-9637439502bf
        Path: /05-hash-tables/02-hash-table-checkpoint.md      
  -
    Title: Heaps
    Description: An alternative binary tree
    UID: 544bdf6a-3e48-48e6-8434-414e21b26fd7
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 4a7e9b34-203d-44c5-ae25-86f815f85576
        Path: /06-heaps/01-heaps.md
      -
        Type: Checkpoint
        UID: 824d3954-8e7f-472e-9878-426197b86f6f
        Path: /06-heaps/02-heaps-exercise-checkpoint.md
  -
    Title: Algorithms
    Description: Divide & Conquer, Greedy and Dynamic Programming
    UID: ccdccab2-b7f3-42d8-977d-955a58ce9d05
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a76dfc02-3b54-459c-bf72-66a072b26119
        Path: /07-algorithms/algorithms.md
      -
        Type: Checkpoint
        UID: 92514af3-c487-40cb-acbc-8b62d864be82
        Path: /07-algorithms/algorithms-checkpoint.md
  -
    Title: Graphs
    Description: Graph Data Structures & Algorithms
    UID: b0d74464-2678-44a8-a4ff-dc74350e7114
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 43ec38b5-3ce1-4882-b709-ca99d4b702c1
        Path: /08-graphs/graphs.md
      -
        Type: Checkpoint
        UID: 8f80f1c3-71f9-42c7-b658-9720f6e3f5b1
        Path: /08-graphs/graphs.checkpoint.md
      -
        Type: Lesson
        UID: f0e4986d-dc1b-441d-8236-4c4de94c4422
        Path: /08-graphs/dijskstra.md
  
